CC=gcc
CFLAGS= -g -Wall -std=gnu99 -D DEBUG_MODE
kozoume: kozoume.o interpreter.o io.o ppu.o memory.o z80.o cartridge.o opcodes.o interrupts.o

clean:
	rm -f kozoume kozoume.exe kozoume.o interpreter.o io.o ppu.o memory.o z80.o cartridge.o opcodes.o interrupts.o
